import { useCallback, useEffect, useState } from 'react';
import { Activity, Cloud, Database, Radio, RefreshCw, Satellite, Ship, Snowflake, TriangleAlert, Waves } from 'lucide-react';
import { AppShell } from '../../components/layout/AppShell';
import { api, clearApiCache } from '../../services/api';

type Feed = { name: string; icon: typeof Activity; status: 'LIVE' | 'DELAYED' | 'UNAVAILABLE'; detail: string; records: string; source?: string };

export default function LiveDataPage() {
  const [feeds, setFeeds] = useState<Feed[]>([]); const [refreshing, setRefreshing] = useState(true); const [updatedAt, setUpdatedAt] = useState('');
  const refresh = useCallback(async () => {
    setRefreshing(true); clearApiCache();
    const [health, vessels, icebergs, environment, telemetry, satellite, alerts, weather] = await Promise.all([api.realtimeHealth(), api.fleet(true), api.icebergs(), api.environmentStatus(), api.vesselTelemetry(), api.realtimeSatelliteScenes({ max_results: 10, use_live_api: true }), api.alerts(), api.weather()]);
    const available = (value: any) => value ? 'LIVE' as const : 'UNAVAILABLE' as const;
    setFeeds([
      { name: 'Backend & real-time engine', icon: Activity, status: available(health), detail: health?.overall_status || health?.status || 'No health response', records: health ? 'Connected' : 'No response', source: health?.provider },
      { name: 'Vessel AIS / NMEA telemetry', icon: Ship, status: available(telemetry || vessels), detail: telemetry?.source || vessels?.source || vessels?.data_status || 'No vessel data received', records: `${telemetry?.vessels?.length || vessels?.total_vessels || vessels?.vessels?.length || 0} vessels`, source: telemetry?.freshness_status },
      { name: 'Iceberg observations', icon: TriangleAlert, status: available(icebergs), detail: (icebergs as any)?.source || 'BYU / US NIC iceberg feed', records: `${icebergs?.icebergs?.length || 0} targets`, source: (icebergs as any)?.observation_date },
      { name: 'Sea-ice environment', icon: Snowflake, status: available(environment), detail: environment?.sea_ice?.source || environment?.source || 'Environmental feed', records: environment?.sea_ice?.status || 'Latest grid', source: environment?.sea_ice?.updated_at },
      { name: 'Weather & waves', icon: Cloud, status: available(weather), detail: weather?.source || 'Weather API', records: weather?.status || 'Latest forecast', source: weather?.observation_time },
      { name: 'Ocean currents', icon: Waves, status: available(environment?.ocean_currents), detail: environment?.ocean_currents?.source || 'Ocean-current feed', records: environment?.ocean_currents?.status || 'Latest model', source: environment?.ocean_currents?.updated_at },
      { name: 'Satellite scenes', icon: Satellite, status: available(satellite), detail: satellite?.cache_stats?.mode || 'Sentinel / provider query', records: `${satellite?.count || satellite?.scenes?.length || 0} scenes`, source: satellite?.cache_stats?.last_updated },
      { name: 'Operational alerts', icon: Radio, status: available(alerts), detail: 'Derived from current navigation state', records: `${alerts?.alerts?.length || 0} alerts`, source: 'Aeolus risk engine' },
    ]);
    setUpdatedAt(new Date().toLocaleTimeString()); setRefreshing(false);
  }, []);
  useEffect(() => { refresh(); const timer = window.setInterval(refresh, 30000); return () => window.clearInterval(timer); }, [refresh]);
  return <AppShell title="LIVE DATA" subtitle="Current API responses and provider health"><div className="min-h-full overflow-y-auto bg-[#f7fbff] p-4 sm:p-6"><div className="mx-auto max-w-6xl"><section className="rounded-2xl bg-[#075a9c] p-6 text-white sm:flex sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#b9eaff]">Data observability</p><h1 className="mt-2 text-3xl font-bold tracking-[-.04em]">Live provider status</h1><p className="mt-2 text-sm text-[#d8f5ff]">This page refreshes every 30 seconds and shows the actual data returned by your configured API services.</p></div><button onClick={refresh} disabled={refreshing} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2 text-xs font-bold text-[#075a9c] disabled:opacity-60 sm:mt-0"><RefreshCw className={refreshing ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} />Refresh now</button></section><div className="mt-5 flex items-center justify-between text-xs text-[#668fa9]"><span>Last checked: {updatedAt || 'Checking…'}</span><span>Environment: {import.meta.env.VITE_API_BASE_URL || import.meta.env.VITE_API_URL || 'same-origin /api proxy'}</span></div><div className="mt-4 grid gap-4 md:grid-cols-2">{feeds.map(feed => <FeedCard key={feed.name} feed={feed} />)}</div><section className="mt-5 rounded-2xl border border-[#d6e9f5] bg-white p-5 text-xs text-[#527c99]"><div className="flex items-center gap-2 font-bold text-[#083b66]"><Database className="h-4 w-4 text-[#168dc5]" />Configuration needed for live mode</div><p className="mt-2 leading-relaxed">Add provider credentials only to the backend environment: <code>OPEN_WATERS_API_KEY</code> for AIS, <code>COPERNICUS_MARINE_USERNAME</code>/<code>COPERNICUS_MARINE_PASSWORD</code> for currents, and enable <code>NMEA_ENABLED</code> with the shipboard feed details for onboard telemetry. Keep keys out of Vite/browser variables.</p></section></div></div></AppShell>;
}
function FeedCard({ feed }: { feed: Feed }) { const Icon = feed.icon; const tint = feed.status === 'LIVE' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : feed.status === 'DELAYED' ? 'border-amber-200 bg-amber-50 text-amber-700' : 'border-rose-200 bg-rose-50 text-rose-700'; return <article className="rounded-2xl border border-[#d6e9f5] bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf8ff] text-[#168dc5]"><Icon className="h-5 w-5" /></span><span className={`rounded-full border px-2 py-1 text-[9px] font-bold tracking-wide ${tint}`}>{feed.status}</span></div><h2 className="mt-4 text-sm font-bold text-[#083b66]">{feed.name}</h2><p className="mt-1 text-xs text-[#638ca8]">{feed.detail}</p><div className="mt-4 flex justify-between border-t border-[#e2eff6] pt-3 text-[11px]"><span className="font-bold text-[#075a9c]">{feed.records}</span><span className="max-w-[45%] truncate text-right text-[#779ab0]">{feed.source || 'No timestamp'}</span></div></article>; }
